-- Create the main table to store games
CREATE TABLE Games (
                       GameID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing primary key
                       StartTimestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, -- Game start timestamp
                       EndTimestamp TIMESTAMP, -- Game end timestamp
                       MyColor VARCHAR(5) NOT NULL, -- The color I am in this game ('White' or 'Black')
                       Status VARCHAR(20) DEFAULT 'Not Finished' NOT NULL, -- Game status ('Finished' or 'Not Finished')
                       Result VARCHAR(5) -- Stores 'White', 'Black', or 'Draw'
);

-- Add a check constraint for MyColor
ALTER TABLE Games ADD CONSTRAINT chk_mycolor CHECK (MyColor IN ('White', 'Black'));

-- Add a check constraint for Result
ALTER TABLE Games ADD CONSTRAINT chk_result CHECK (Result IN ('White', 'Black', 'Draw'));

-- Create the table to store the game positions
CREATE TABLE Positions (
                           PositionID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing primary key
                           GameID INT NOT NULL, -- Foreign key to Games table
                           PositionNumber INT NOT NULL, -- Number of the position in the game
                           FENString VARCHAR(100) NOT NULL, -- Board state in FEN notation
                           FOREIGN KEY (GameID) REFERENCES Games(GameID) ON DELETE CASCADE
);

-- Create the table to store game moves
CREATE TABLE Moves (
                       GameID INT NOT NULL, -- Foreign key referencing the Games table
                       MoveID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing primary key
                       PositionID INT NOT NULL, -- Foreign key to Positions table
                       MoveNumber INT NOT NULL, -- Sequential move number
                       PlayerTurn VARCHAR(5) NOT NULL, -- 'White' or 'Black'
                       MoveNotation VARCHAR(20) NOT NULL, -- Chess move notation (e.g., 'e4', 'Nf3')
                       Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, -- Timestamp of the move
                       FOREIGN KEY (GameID) REFERENCES Games(GameID) ON DELETE CASCADE,
                       FOREIGN KEY (PositionID) REFERENCES Positions(PositionID) ON DELETE CASCADE
);

-- Add a check constraint for PlayerTurn
ALTER TABLE Moves ADD CONSTRAINT chk_playerturn CHECK (PlayerTurn IN ('White', 'Black'));

-- Create the table to store the game players
CREATE TABLE Players (
                             GameID INT NOT NULL,
                             MyColor VARCHAR(5) NOT NULL,
                             OpponentColor VARCHAR(5) NOT NULL,
                             MyCapturedPieces VARCHAR(100),
                             OpponentCapturedPieces VARCHAR(100),
                             FOREIGN KEY (GameID) REFERENCES Games(GameID) ON DELETE CASCADE
);

ALTER TABLE Players ADD CONSTRAINT chk_mycolor_players CHECK (MyColor IN ('White', 'Black'));
ALTER TABLE Players ADD CONSTRAINT chk_opponentcolor CHECK (OpponentColor IN ('White', 'Black'));
